# server configurations
[server]
    # server name
    name =              "qbcore-rp"
    # server description (max 127 characters)
    description =       "Official roleplay server using only QBCore packages!"
    # max players
    max_players =       64
    # leave it blank for no password
    password =          ""
    # server IP. we recommend leaving it 0.0.0.0 for default
    ip =                "0.0.0.0"
    # server port (TCP and UDP)
    port =              7777
    # server tick rate in milliseconds (dangerous! server will tick at each [tick_rate] ms, affecting both server and client performance. 33 ms means 30 ticks per second and is the default and recommended value)
    tick_rate =         33
    # log Level. (1) normal - (2) debug - (3) verbose
    log_level =         2

# HELIX configurations
[world]
    # game-mode package to load (set the main game-mode package to load - you can load only one 'game-mode' package type at once)
    game_mode =         "qb-core"
    # packages list (set the packages you want to load)
    packages = [
        "qb-target",
        "qb-interior",
        "qb-apartments",
        "qb-houses",
        "qb-multicharacter",
        "qb-spawn",
        "qb-hud",
        "qb-inventory",
        "qb-weapons",
        "qb-smallresources",
        "qb-adminmenu",
        "qb-radialmenu",
        "qb-minigames",
        "qb-shops",
        "qb-banking",
        "qb-ambulancejob",
        "qb-policejob",
        "qb-radio",
    ]
    # asset packs list (this will additionally load the asset packs you define here)
    assets = [
        "ecdbd-fh-downtown-tits",
        "abcca-qbcore",
        "abcca-shells",
        "ecdbd-h",
        "qbcore-vehicles-mm",
    ]
    # default startup map
    map =               "ecdbd-fh-downtown-tits::RP_Downtown_Tits_v2"
    # banned HELIX account IDs
    banned_ids = [
        
    ]
